[theme]
base = "light"
primaryColor = "#00622F"
backgroundColor = "#F5FAF7"
secondaryBackgroundColor = "#DCEAE2"
textColor = "#1A1A1A"
font = "sans serif"
supabase_dp_url = "postgresql://postgres:AblazeBe_2517@db.hbtrudgysaupjdddsstn.supabase.co:5432/postgres"
